<a href="https://colab.research.google.com/github/Qalb-e-Momin777/my_notebook.ipynb/blob/main/my_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
scalar = torch.tensor(100)
scalar , scalar.item() , scalar.ndim

(tensor(100), 100, 0)

Scalar is a zero dimensional tensor

In [ ]:
vector = torch.tensor([1,2,3])
vector , vector.shape , vector.ndim

(tensor([1, 2, 3]), torch.Size([3]), 1)

Vector is a single dimensional tensor but contain many elements here 3 element in my vector

In [ ]:
Matrix = torch.tensor([[1,2,3,4],[5,6,7,8]])
Matrix , Matrix.shape , Matrix.ndim

(tensor([[1, 2, 3, 4],
         [5, 6, 7, 8]]),
 torch.Size([2, 4]),
 2)

Matrix is 2-Dimensional tensor

In [ ]:
Tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
Tensor , Tensor.shape , Tensor.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

Tensor with more than 2 dimensions


In [ ]:
random = torch.rand(3,4)
random , random.shape , random.item

(tensor([[0.8317, 0.1433, 0.0420, 0.6956],
         [0.4726, 0.6927, 0.2549, 0.4722],
         [0.6688, 0.6708, 0.7066, 0.1115]]),
 torch.Size([3, 4]),
 <function Tensor.item>)

Here a random tensor is created with 3 rows and 4 columns

In [ ]:
random_tensor_image = torch.rand(224,224,3)
random_tensor_image

tensor([[[7.9348e-01, 4.4678e-01, 3.1166e-02],
         [8.3048e-01, 9.0844e-01, 3.7586e-01],
         [6.0849e-01, 9.8422e-02, 5.2870e-01],
         ...,
         [3.8135e-02, 5.9443e-01, 9.5990e-02],
         [8.1054e-01, 1.5513e-01, 9.0528e-01],
         [3.6376e-01, 9.4019e-01, 1.6690e-01]],

        [[6.6143e-01, 8.6843e-01, 1.9146e-01],
         [6.6543e-01, 6.7266e-01, 3.6948e-01],
         [3.0625e-04, 1.8434e-01, 7.0245e-01],
         ...,
         [8.2179e-01, 2.2175e-01, 9.7100e-01],
         [7.4168e-01, 1.3216e-01, 4.3780e-01],
         [2.8558e-01, 7.8693e-01, 1.3779e-01]],

        [[9.3239e-01, 1.0764e-01, 3.9296e-02],
         [5.3122e-01, 3.6278e-01, 7.9090e-01],
         [1.9051e-01, 2.1075e-01, 3.1716e-01],
         ...,
         [1.8859e-01, 6.2123e-01, 6.0366e-01],
         [2.9126e-02, 7.0173e-02, 3.5189e-01],
         [1.5293e-01, 4.3332e-01, 3.2743e-01]],

        ...,

        [[4.9094e-01, 8.9401e-01, 5.0406e-01],
         [9.9078e-01, 5.9339e-01, 7.0810e-01]

Here a image representation in form of tensor
here size(224,224,3) repesent HWC means Height, Width , Color_Channel(red,green.blue)

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

These functions are fundamental in deep learning because they serve as building blocks for initializing, masking, and structuring data.

In [ ]:
ones = torch.ones(3,4)
ones , ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 torch.int64)

These functions are fundamental in deep learning because they serve as building blocks for initializing, masking, and structuring data.

In [ ]:
# Tensor range
one_to_twenty = torch.arange(1,20,2)
one_to_twenty

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Here A tensor Range that start from 1 and end on 20 and also take 2 step

In [ ]:
# Tensor Like
one_to_ten_zeros = torch.zeros_like(input = one_to_twenty)
one_to_ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

These functions create new tensors filled with zeros or ones that have the same shape, data type, and device as an existing tensor.

In [ ]:
#Tensor Attribute
import torch
some_tensor = torch.rand(3,4)
some_tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


Matrix Manipulation(Tensor Operations)
1. Addition
2. Division
3. Multiplication
4. Subtraction
5. Matrix Multiplication
    Two types of Matrix Multiplication
    1. Element vise multiplication
    2. Matrix multiplication
    two rules of Multiplications
    1. The inner dimension must match
        2x3  3x2 (satisfies)
    2. The resulting Matric has shape of Outer Dimensions

In [ ]:
import torch
Tensor = torch.tensor([1,2,3,4])
print(Tensor + 10)
print(Tensor - 10)
print(Tensor * 10)
print(Tensor / 10)
# Built In Function
print(torch.add(Tensor,10))
print(torch.sub(Tensor,10))
print(torch.mul(Tensor,10))
print(torch.div(Tensor,10))
print(torch.matmul(Tensor,Tensor))


tensor([11, 12, 13, 14])
tensor([-9, -8, -7, -6])
tensor([10, 20, 30, 40])
tensor([0.1000, 0.2000, 0.3000, 0.4000])
tensor([11, 12, 13, 14])
tensor([-9, -8, -7, -6])
tensor([10, 20, 30, 40])
tensor([0.1000, 0.2000, 0.3000, 0.4000])
tensor(30)


Important Error in Deep Learning: Shape Error

In [ ]:
print(torch.matmul(torch.rand(3,2) , torch.rand(3,2)))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# at operator is also used for multiplications
import torch
tensor = torch.tensor([1,2,3])
print(tensor @ tensor)

tensor(14)


In [ ]:
# to fix our shape error we can manipulate one of our tensor using a tranpose
tensor_1 = torch.rand(3,2)
tensor_2 = torch.rand(3,2)
print(tensor_2.T.shape)
print(tensor_1 @ tensor_2.T)

torch.Size([2, 3])
tensor([[0.5743, 0.2437, 0.2614],
        [0.7303, 0.3373, 0.3570],
        [1.0425, 1.0324, 1.0028]])


In [ ]:
tensor = torch.arange(0,100,10)
print(f"Minimum: {tensor.min()}")
print(f"Maximum: {tensor.max()}")
print(f"Sum: {tensor.sum()}")
print(f"Mean: {tensor.type(torch.float32).mean()}")
print(f"Positional Max : {tensor.argmax()}")
print(f"Positional Min : {tensor.argmin()}")

Minimum: 0
Maximum: 90
Sum: 450
Mean: 45.0
Positional Max : 9
Positional Min : 0


In [ ]:
import torch

Reshaping : Reshape an input tensor in defined shape
Viewing : Work same as reshape but also change the original tensor
Stacking : combine multiple tensor on top of each tensor (vstack , hstack)
Squeeze : remove 1 dimension in the input tensor
unsqueeze : add 1 dimension to an input tensor


In [ ]:
# Reshaping , Viewing , Stacking
x = torch.arange(1,11)
print(x , x.shape)
print(x.reshape(2,5))
print(x)
print(x.view(1,10))



tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) torch.Size([10])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])


In [ ]:
# squeeze and unsqueeze
x = torch.tensor([[1,2,3,4,5]])
print(x , x.shape)
print(f"After Squuezing : {x.squeeze() , x.squeeze().shape}")
print(f"After Unsqueezing : {x.unsqueeze(dim=0) , x.unsqueeze(dim=1).shape}")

tensor([[1, 2, 3, 4, 5]]) torch.Size([1, 5])
After Squuezing : (tensor([1, 2, 3, 4, 5]), torch.Size([5]))
After Unsqueezing : (tensor([[[1, 2, 3, 4, 5]]]), torch.Size([1, 1, 5]))


In [ ]:
# Permute
import torch
x = torch.rand(224,224,3)
print(f"Before Permutation : {x.shape}")
print(f"After Permutation : {x.permute(2,0,1).shape}")

Before Permutation : torch.Size([224, 224, 3])
After Permutation : torch.Size([3, 224, 224])


Permutation
reordering the dimension of tensor

In [ ]:
# Indexing in Tensor
x = torch.arange(1,10).reshape(1,3,3)
print(x , x.shape)
print(f"First Square Bracket : {x[0]}")
print(f"Second Square Bracket : {x[0][0]}")
print(f"Third Square Bracket : {x[0][0][0]}")

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
First Square Bracket : tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second Square Bracket : tensor([1, 2, 3])
Third Square Bracket : 1


Indexing is a process to slect specific data in tensors

In [2]:
# Pytorch and Numpy
# # Two Method used
# 1. torch.from_numpy(ndarray)
# 2. torch.Tensor.numpy()

In [10]:
import numpy as np
import torch
# numpy to tensor
x = np.arange(7)
numpy_to_tensor = torch.from_numpy(x)
x = x+1
x , numpy_to_tensor
# tensor to numpy
t = torch.arange(7)
tensor_to_numpy = t.numpy()
t.dtype , tensor_to_numpy.dtype



(torch.int64, dtype('int64'))

# Reproducibility
in short how neural network learn
start with random number --> tensor operation --> update tensor number to try and make better representation for the data --> again --> again --> again

Essentially the random seed does is flavour the randomness

In [14]:
import torch
tensor_A  = torch.rand(3,4)
tensor_B  = torch.rand(3,4)
print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [17]:
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_A  = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
tensor_B  = torch.rand(3,4)
print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [19]:
!nvidia-smi

Sun May  3 19:44:07 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8             11W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [21]:
# Check GPU is available
import torch
torch.cuda.is_available()

True

In [24]:
# Setup Device
Device = "cuda" if torch.cuda.is_available() else "cpu"
print(torch.cuda.device_count())
Device

1


'cuda'