<a href="https://colab.research.google.com/github/Qalb-e-Momin777/my_notebook.ipynb/blob/main/my_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import torch
scalar = torch.tensor(100)
scalar , scalar.item() , scalar.ndim

(tensor(100), 100, 0)

Scalar is a zero dimensional tensor

In [44]:
vector = torch.tensor([1,2,3])
vector , vector.shape , vector.ndim

(tensor([1, 2, 3]), torch.Size([3]), 1)

Vector is a single dimensional tensor but contain many elements here 3 element in my vector

In [45]:
Matrix = torch.tensor([[1,2,3,4],[5,6,7,8]])
Matrix , Matrix.shape , Matrix.ndim

(tensor([[1, 2, 3, 4],
         [5, 6, 7, 8]]),
 torch.Size([2, 4]),
 2)

Matrix is 2-Dimensional tensor

In [46]:
Tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
Tensor , Tensor.shape , Tensor.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

Tensor with more than 2 dimensions


In [50]:
random = torch.rand(3,4)
random , random.shape , random.item

(tensor([[0.8317, 0.1433, 0.0420, 0.6956],
         [0.4726, 0.6927, 0.2549, 0.4722],
         [0.6688, 0.6708, 0.7066, 0.1115]]),
 torch.Size([3, 4]),
 <function Tensor.item>)

Here a random tensor is created with 3 rows and 4 columns

In [51]:
random_tensor_image = torch.rand(224,224,3)
random_tensor_image

tensor([[[7.9348e-01, 4.4678e-01, 3.1166e-02],
         [8.3048e-01, 9.0844e-01, 3.7586e-01],
         [6.0849e-01, 9.8422e-02, 5.2870e-01],
         ...,
         [3.8135e-02, 5.9443e-01, 9.5990e-02],
         [8.1054e-01, 1.5513e-01, 9.0528e-01],
         [3.6376e-01, 9.4019e-01, 1.6690e-01]],

        [[6.6143e-01, 8.6843e-01, 1.9146e-01],
         [6.6543e-01, 6.7266e-01, 3.6948e-01],
         [3.0625e-04, 1.8434e-01, 7.0245e-01],
         ...,
         [8.2179e-01, 2.2175e-01, 9.7100e-01],
         [7.4168e-01, 1.3216e-01, 4.3780e-01],
         [2.8558e-01, 7.8693e-01, 1.3779e-01]],

        [[9.3239e-01, 1.0764e-01, 3.9296e-02],
         [5.3122e-01, 3.6278e-01, 7.9090e-01],
         [1.9051e-01, 2.1075e-01, 3.1716e-01],
         ...,
         [1.8859e-01, 6.2123e-01, 6.0366e-01],
         [2.9126e-02, 7.0173e-02, 3.5189e-01],
         [1.5293e-01, 4.3332e-01, 3.2743e-01]],

        ...,

        [[4.9094e-01, 8.9401e-01, 5.0406e-01],
         [9.9078e-01, 5.9339e-01, 7.0810e-01]

Here a image representation in form of tensor
here size(224,224,3) repesent HWC means Height, Width , Color_Channel(red,green.blue)